In [2]:
import numpy as np
import pandas as pd

### Q1. Pandas version

In [3]:
pd.__version__

'3.0.6'

```python
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'
df = pd.read_csv(url)
```

In [10]:
import os
os.getcwd()

'/home/moonk/projects/ml-zoomcamp/01-intro'

In [13]:
df = pd.read_csv('./data/car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

### Q2. Records count

In [15]:
df.shape

(9704, 11)

### Q3. Fuel types

In [17]:
df['fuel_type'].nunique()

2

In [16]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

### Q4. Missing values

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   str
 7   fuel_type            9704 non-null   str
 8   drivetrain           9704 non-null   str
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), str(3)
memory usage: 834.1 KB

In [20]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

### Q5. Max fuel efficiency

In [26]:
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

### Q6. Median value of horsepower

In [39]:
df['horsepower']

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [50]:
df['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [49]:
df['horsepower'].median()

np.float64(149.0)

In [37]:
df['horsepower'].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ...
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

```python
type(df['horsepower'].mode())

pandas.Series
```

In [47]:
df['horsepower'].fillna(df['horsepower'].mode()[0])

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [48]:
df['horsepower'].fillna(df['horsepower'].mode()[0]).median()

np.float64(152.0)

### Q7. Sum of weights

In [51]:
df['origin'] == 'Asia'

0       False
1       False
2       False
3       False
4       False
        ...
9699    False
9700    False
9701    False
9702    False
9703     True
Name: origin, Length: 9704, dtype: bool

```python
df_Asia = df.loc[df['origin'] == 'Asia', :]
df_Asia.head()
```

In [59]:
df_Asia = df[df['origin'] == 'Asia']
df_Asia.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730

In [68]:
df_Asia.loc[:, ['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [78]:
X = df_Asia.loc[:, ['vehicle_weight', 'model_year']][:7].to_numpy()

In [82]:
X.T.dot(X)

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [83]:
np.linalg.inv(X.T.dot(X))

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [84]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [85]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

In [86]:
w

array([0.01386421, 0.5049067 ])

In [88]:
np.sum(w)

np.float64(0.5187709081074016)